### ISSUE TITLE
Unidentifed developer error

### ISSUE THREAD

**Issue by patrickrushton** [diracdeltas/vstSpleeter#18]
The Reddit thread linked in step four for fixing the error has been deleted

EDIT: found it via wayback machine
`sudo xattr -rd com.apple.quarantine /Library/Audio/Plug-Ins/VST3/spleeter-dj.vst3`

**Comment by diracdeltas** [comment]
which step 4 are you referring to?

i see i linked the reddit thread in https://github.com/diracdeltas/vstSpleeter/issues/4#issuecomment-634195448 so i edited that to include the archived url

**Comment by patrickrushton** [comment]
Yes it would have helped if I mentioned what I was referring to. The [installation instructions for 0.3](https://github.com/diracdeltas/vstSpleeter/releases/tag/0.3)
