### ISSUE TITLE
unidentified developer error in MacOS 10.15

### ISSUE THREAD

**Issue by tambdev** [diracdeltas/vstSpleeter#4]
I tried loading the VST following the instructions provided [here](https://github.com/diracdeltas/vstSpleeter/releases/tag/0.3), but when i try to rescan the plugins via ableton settings, it prompts the "unspecified author" error.

If i try to click "Open anyways" in the "Security & Privacy" window, the error message just stays there and the vst still isn't showing up in the plugin panel

Ableton Live 10 Suite 10.1.4
MacOS Catalina 10.15.4, MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)

Thanks in advance

**Comment by diracdeltas** [comment]
> it prompts the "unspecified author" error.

can you post a screenshot of this? any other details? i haven't seen this error come up on MacOS.

i did all testing on Mojave btw

**Comment by mangowh** [comment]
<img width="914" alt="Screenshot 2020-05-26 at 09 16 09" src="https://user-images.githubusercontent.com/17550149/82871244-9037a080-9f31-11ea-8e1b-374a689d89c5.png">

When i toggle the respective folder button in Ableton, it just prompts the error and it does not disappear when i click on "Open Anyway" from the settings panel. I recorded this strange behaviour, [here's a link](https://we.tl/t-O4UFcDet28) when you can download it if that can help. After that, there's no trace of any new plugin in the ableton plug-ins > VST3 folder. 

I already tried unzipping the zip both with another tool (the unarchiver).
This problem already happened sometimes with other vsts, but once i clicked open anyway they all correctly loaded.

Let me know if you need any more info

**Comment by diracdeltas** [comment]
@tambdev this seems to be an apple bug. try this workaround: https://www.reddit.com/r/MacOS/comments/dpue7j/2019_macbook_pro_running_catalina_unidentified/f60q1kd/ (edit: [see here for archived URL](https://web.archive.org/web/20230130094354/https://www.reddit.com/r/MacOS/comments/dpue7j/2019_macbook_pro_running_catalina_unidentified/f60q1kd/?utm_medium=web2x&utm_source=share))

where it says "Drag and drop the app into the Terminal window right after the above command.", i believe you need to drop the unzipped spleeter-dj.vst3 file.

**Comment by mangowh** [comment]
Okay! That actually worked out, but i had to rename the file to trick ableton to think it was a different one (replacing it wasn't enough)

Thank you !
